### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by joedirt19871** [TtvNekix/nekix_vehicleshop#1]
[script:nek_vehiclesh] SCRIPT ERROR: @nek_vehicleshop/server/core.lua:104: attempt to call a nil value (field 'showNotification')
[script:nek_vehiclesh] SCRIPT ERROR: @nek_vehicleshop/server/core.lua:87: attempt to call a nil value (field 'showNotification')

**Comment by guillerp8** [comment]
That's because you are using ESX 1.1 . Update your extended c that's deprectated as f XD

**Comment by TtvNekix** [comment]
> That's because you are using ESX 1.1 . Update your extended c that's deprectated as f XD

Voy a tener que convertirlo a 1.1 y 1.2
