### ISSUE TITLE
Multiple car spawns

### ISSUE THREAD

**Issue by soniXx123** [TtvNekix/nekix_vehicleshop#2]
Hello, we have a server with a couple of hundred players and for every player, he spawns a car :D I guess you know what chaos we had lol Possible to fix this? because we like the render system and this is performance friendly.

**Comment by soniXx123** [comment]
![image](https://user-images.githubusercontent.com/35350615/130373070-f5464a74-3b67-4f88-b4e5-f133becbb8ac.png)

2 devs on my server

**Comment by TtvNekix** [comment]
I release a new version. Update it. And check if works now. Sorry.

**Comment by soniXx123** [comment]
nope is still :( 

![image](https://user-images.githubusercontent.com/35350615/130392614-115da648-c65f-4c4b-8232-f417e20b7b50.png)

**Comment by TtvNekix** [comment]
Ok i Will test it un my server

**Comment by soniXx123** [comment]
if you need, we can test it on my test dev server.
